const lessons = {
  "Chuyên ngành": {
    "Từ vựng": [
      { "reading": "じこせつめいしょ", "kanji": "事故説明書", "meaning": "Bảng hướng dẫn sự cố" },
      { "reading": "しゅっかじかん", "kanji": "出荷時間", "meaning": "Thời gian xuất hàng" },
      { "reading": "のうひんじかん", "kanji": "納品時間", "meaning": "Thời gian giao hàng" },
      { "reading": "でんぴょう", "kanji": "伝票", "meaning": "Tờ phiếu" },
      { "reading": "けしゴム", "kanji": "消しゴム", "meaning": "Cục tẩy" },
      { "reading": "にっぽう", "kanji": "日報", "meaning": "Báo cáo ngày" },
      { "reading": "ほうこくしょ", "kanji": "報告書", "meaning": "Bảng báo cáo" },
      { "reading": "だんボール", "kanji": "段ボール", "meaning": "Thùng giấy" },
      { "reading": "せきにんしゃ", "kanji": "責任者", "meaning": "Người phụ trách" },
      { "reading": "きかい", "kanji": "機械", "meaning": "Máy móc" },
      { "reading": "ふりょうひん", "kanji": "不良品", "meaning": "Hàng lỗi" },
      { "reading": "れいぞうこ", "kanji": "冷蔵庫", "meaning": "Tủ mát" },
      { "reading": "じょうおんこ", "kanji": "常温庫", "meaning": "Tủ nhiệt độ thường" },
      { "reading": "れいとうこ", "kanji": "冷凍庫", "meaning": "Tủ đông" },
      { "reading": "さぎょうふく", "kanji": "作業服", "meaning": "Quần áo đi làm" },
      { "reading": "かじょう", "kanji": "過剰", "meaning": "Quá tải, quá mức" },
      { "reading": "しょうひんじこ", "kanji": "商品事故", "meaning": "Sự cố hàng hóa" },
      { "reading": "こうたい", "kanji": "交代", "meaning": "Thay phiên" },
      { "reading": "かくにん", "kanji": "確認", "meaning": "Xác nhận" },
      { "reading": "ていし", "kanji": "停止", "meaning": "Dừng lại" },
      { "reading": "ちゅうし", "kanji": "中止", "meaning": "Hủy bỏ" },
      { "reading": "そうじ", "kanji": "掃除", "meaning": "Vệ sinh" },
      { "reading": "けんぴん", "kanji": "検品", "meaning": "Kiểm hàng" },
      { "reading": "ふりょう", "kanji": "不良", "meaning": "Hàng hỏng" },
      { "reading": "でんち", "kanji": "電池", "meaning": "Cục pin" },
      { "reading": "じこ", "kanji": "事故", "meaning": "Sự cố" },
      { "reading": "ほうこく", "kanji": "報告", "meaning": "Báo cáo" },
      { "reading": "だいしゃ", "kanji": "台車", "meaning": "Xe đẩy" },
      { "reading": "てをあらう", "kanji": "手を洗う", "meaning": "Rửa tay" },
      { "reading": "しょうどく", "kanji": "消毒", "meaning": "Khử trùng" },
      { "reading": "じむしつ", "kanji": "事務室", "meaning": "Văn phòng" },
      { "reading": "しょうひん", "kanji": "商品", "meaning": "Sản phẩm" },
      { "reading": "にもつ", "kanji": "荷物", "meaning": "Hành lý" },
      { "reading": "にっきん", "kanji": "日勤", "meaning": "Ca ngày" },
      { "reading": "やきん", "kanji": "夜勤", "meaning": "Ca đêm" },
      { "reading": "ストップ", "kanji": "", "meaning": "Dừng lại" },
      { "reading": "ボールペン", "kanji": "", "meaning": "Bút bi" },
      { "reading": "マジック", "kanji": "", "meaning": "Bút lông" },
      { "reading": "カッター", "kanji": "", "meaning": "Dao rọc" },
      { "reading": "１びん", "kanji": "１便", "meaning": "Chuyến 1" },
      { "reading": "２びん", "kanji": "２便", "meaning": "Chuyến 2" },
      { "reading": "すぐします", "kanji": "", "meaning": "Lập tức làm ngay" },
      { "reading": "いっしょにします", "kanji": "", "meaning": "Cùng làm" },
      { "reading": "わけています", "kanji": "分けています", "meaning": "Chia ra" },
      { "reading": "シール", "kanji": "", "meaning": "Tem dán" },
      { "reading": "トイレ・おてあらい", "kanji": "トイレ・お手洗い", "meaning": "Nhà vệ sinh" },
      { "reading": "スイッチ", "kanji": "", "meaning": "Công tắc" },
      { "reading": "リフト", "kanji": "", "meaning": "Xe nâng" },
      { "reading": "パレット", "kanji": "", "meaning": "Pallet" },
      { "reading": "ライン", "kanji": "", "meaning": "Chuyền" },
      { "reading": "トラック", "kanji": "", "meaning": "Xe tải" },
      { "reading": "パソコン", "kanji": "", "meaning": "Máy tính" },
      { "reading": "ゴミぶくろ", "kanji": "ゴミ袋", "meaning": "Túi rác" },
      { "reading": "ハンディ", "kanji": "", "meaning": "Máy đọc mã vạch" },
      { "reading": "コンテナ", "kanji": "", "meaning": "Khay, rổ" }
    ]
  }
};